[tool.poetry]
name = "2"
version = "0.1.0"
description = ""
authors = ["NikYurchik <14urka@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
psycopg2 = "^2.9.6"
faker = "^19.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
