"""Change contacts

Revision ID: d97ecef99959
Revises: 3065aa5747ba
Create Date: 2023-08-27 23:15:23.487420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97ecef99959'
down_revision: Union[str, None] = '3065aa5747ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_unique_constraint('unique_email_user', 'contacts', ['email', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email_user', 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    # ### end Alembic commands ###
