"""Add contacts.days_of_year

Revision ID: fbd2d428f077
Revises: 7f83cce19a36
Create Date: 2023-08-26 18:44:44.629609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd2d428f077'
down_revision: Union[str, None] = '7f83cce19a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('days_of_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'days_of_year')
    # ### end Alembic commands ###
